# Generated by Django 3.0.7 on 2020-06-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20200628_0621'),
        ('users', '0003_profile_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='warehouse.Warehouse'),
        ),
    ]
