# Generated by Django 3.0.7 on 2020-06-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20200628_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='delivery_boy',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
